# Generated by Django 3.2.9 on 2021-11-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=None),
        ),
    ]
